{{- if .Values.eks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-cloud-manager-operator
  namespace: {{ .Values.eks.cloudManager.namespace }}
{{ include "rhai-on-xks-chart.imagePullSecrets" . }}
{{- end }}
